# For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml

runtime: aspnetcore
api_version: '2.0'
env: flexible
threadsafe: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5

env_variables:
